"""remove assigned_doctor

Revision ID: cbcfb8fe20a5
Revises: 4cbc6db4a0ff
Create Date: 2026-05-21 10:23:20.819512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbcfb8fe20a5'
down_revision: Union[str, Sequence[str], None] = '4cbc6db4a0ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'assigned_doctor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('assigned_doctor', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
